repos:
  - repo: local
    hooks:
      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --all-features --fix --allow-dirty -- --deny warnings
        language: system
        pass_filenames: false
        files: \.rs$

      - id: rustfmt
        name: rustfmt
        entry: cargo fmt --all --check
        language: system
        pass_filenames: false

      - id: assumls-check
        name: assumls check
        entry: cargo run --quiet -- check src
        language: system
        pass_filenames: false
        always_run: true
